version: '3'

services:
  gateway_db:
    image: postgres:10.4
    volumes:
      - gatewaydb:/var/lib/postgresql/data/
  gateway_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - gateway_db

  aquarius_db:
    image: postgres:10.4
    volumes:
      - aquariusdb:/var/lib/postgresql/data/
  aquarius_web:
    build: aquarius/
    entrypoint: /code/aquarius/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - aquarius_db

  fornax_db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax_web:
    build: fornax/
    entrypoint: /code/fornax/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - fornax_db

  libra_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - libradb:/var/lib/mysql
  libra_web:
    build: libra/
    entrypoint: /code/libra/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    depends_on:
      - libra_db

  capricorn_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - capricorndb:/var/lib/mysql
  capricorn_web:
    build: bag-repository/
    entrypoint: /code/bag-repository/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - capricorn_db

volumes:
  gatewaydb:
  aquariusdb:
  fornaxdb:
  libradb:
  capricorndb:
