version: '3'

services:
  zodiac-db:
    image: postgres:10.4
    volumes:
      - zodiacdb:/var/lib/postgresql/data/
    networks:
      - microservices
  zodiac-web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    networks:
      - microservices
      # - aurora_default
    ports:
      - "8001:8001"
    depends_on:
      - zodiac-db

  pisces-db:
    image: postgres:10.4
    volumes:
      - piscesdbvolume:/var/lib/postgresql/data/
    networks:
      - microservices
  pisces-web:
    build: pisces/
    entrypoint: /code/pisces/entrypoint.sh
    volumes:
      - .:/code
    networks:
      - microservices
    ports:
      - "8007:8007"
    depends_on:
      - pisces-db

  scorpio-db:
    image: postgres:10.4
    volumes:
      - scorpiodbvolume:/var/lib/postgresql/data/
    networks:
      - microservices
  scorpio-web:
    build: scorpio/
    entrypoint: /code/scorpio/entrypoint.sh
    volumes:
      - .:/code
    networks:
      - microservices
    ports:
      - "8008:8008"
    depends_on:
      - scorpio-db

  my-rabbit:
    image: rabbitmq:3-management
    networks:
      - microservices

volumes:
  zodiacdb:
  piscesdbvolume:
  scorpiodbvolume:

networks:
  microservices:
