version: '3'

services:
  gateway_db:
    image: postgres:10.4
    volumes:
      - gatewaydb:/var/lib/postgresql/data/
  gateway_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - gateway_db

  aquarius_db:
    image: postgres:10.4
    volumes:
      - aquariusdb:/var/lib/postgresql/data/
  aquarius_web:
    build: aquarius/
    entrypoint: /code/aquarius/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - aquarius_db

  fornax_db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax_web:
    build: fornax/
    entrypoint: /code/fornax/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8003:8003"
    depends_on:
      - fornax_db

  libra_db:
    image: postgres:10.4
    volumes:
      - libradb:/var/lib/postgresql/data/
  libra_web:
    build: libra/
    entrypoint: /code/libra/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8004:8004"
    depends_on:
      - libra_db

  ursa_major_db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ursamajordb:/var/lib/mysql
  ursa_major_web:
    build: ursa_major/
    entrypoint: /code/ursa_major/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8005:8005"
    depends_on:
      - ursa_major_db

  gemini_db:
    image: postgres:10.4
    volumes:
      - geminidb:/var/lib/postgresql/data/
  gemini_web:
    build: gemini/
    entrypoint: /code/gemini/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8006:8006"
    depends_on:
      - gemini_db

volumes:
  gatewaydb:
  aquariusdb:
  fornaxdb:
  libradb:
  ursamajordb:
  geminidb:
