version: '3'

services:
  gateway_db:
    image: postgres:10.4
    volumes:
      - gatewaydb:/var/lib/postgresql/data/
  gateway_web:
    build: .
    entrypoint: /code/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - gateway_db

  aquarius_db:
    image: postgres:10.4
    volumes:
      - aquariusdb:/var/lib/postgresql/data/
  aquarius_web:
    build: aquarius/
    entrypoint: /code/aquarius/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8001:8001"
    depends_on:
      - aquarius_db

  fornax_db:
    image: postgres:10.4
    volumes:
      - fornaxdb:/var/lib/postgresql/data/
  fornax_web:
    build: fornax/
    entrypoint: /code/fornax/entrypoint.sh
    volumes:
      - .:/code
    ports:
      - "8002:8002"
    depends_on:
      - fornax_db

volumes:
  gatewaydb:
  aquariusdb:
  fornaxdb:
